on:
  push:
    branches:
      - main
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_THEMES: false
          TOKEN: ${{ secrets.TOKEN }}
